type = "Oasis"
entrypoint = "open_oasis.dweam_game:OasisGame"
repo_link = "https://github.com/XmYx/open-oasis"
thumbnail_dir = "thumbnails"

# Game-specific metadata
[games.minecraft]
title = "Oasis Minecraft"
tags = ["Minecraft"]
description = "Decart and Etched's 500M Minecraft model"

[games.minecraft.buttons]
"â¬†ï¸ Up" = "W"
"â¬…ï¸ Left" = "A"
"â¬‡ï¸ Down" = "S"
"â¡ï¸ Right" = "D"
"ğŸ†™ Jump" = "Space"
"ğŸ‘€ Look Around" = "Mouse Movement"
"ğŸ”„ Reset" = "Enter"